ALTER TABLE qa_messages
    ADD COLUMN IF NOT EXISTS intent VARCHAR(64),
    ADD COLUMN IF NOT EXISTS degraded BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS degrade_reason VARCHAR(255),
    ADD COLUMN IF NOT EXISTS fallback_mode VARCHAR(64);
